---
fqdn: beta.ceph.io
install_dir: /opt/www
branch: master
update_frequency: 5
## TODO: Add ceph.io (root domain) to this list
letsencrypt_domains:
  - "*.ceph.io"
letsencrypt_email: ceph-infra@redhat.com
packages:
  - nginx
  - nginx-extras
  - certbot
  - python3-certbot-nginx
  - npm
  - vim
  - net-tools
